name=TEA5767Radio
version=1.0.0
author=IsraEB
maintainer=IsraEB <sr.enriquez@yahoo.com>
sentence=Library for TEA5767 FM radio module.
paragraph=Arduino library to control TEA5767 FM radio modules over I2C.
category=Communication
license=MIT